### ISSUE TITLE
2024.2 support?

### ISSUE THREAD

**Issue by MrSnoozles** [mallowigi/EditorGroups#13]
Hi,

are there plans to support the 2024.2 and up versions of the Jetbrains IDEs? I'm still on 2024.1 because this plugin is just way too useful.

**Comment by sulikdan** [comment]
For those, who are wonderign, got word from @mallowigi that new version/upgrade is being worked on.

**Comment by mallowigi** [comment]
Version 3 will be available soon. I will release an EAP shortly.
